{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Tic Tac Toe Game"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def TicTacToe():\n",
    "    import random\n",
    "    players = []\n",
    "\n",
    "    for i in range(1,3):\n",
    "        print(\"\\n\")\n",
    "        player = input(\"Enter player's name: \")                         #Read Players' names\n",
    "        players.append(player)\n",
    "\n",
    "    play = random.randint(1,2)\n",
    "\n",
    "    if(play == 1):\n",
    "        p1 = players[0]\n",
    "        p2 = players[1]\n",
    "        print(\"\\n\")\n",
    "        print(p1, \"is 'X' and\", p2, \"is 'O'  (Randomly alloted)\" )                          \n",
    "                                                                     #Randomly allot X and O\n",
    "    elif(play == 2):\n",
    "        p1 = players[1]\n",
    "        p2 = players[0]\n",
    "        print(\"\\n\")\n",
    "        print(p1, \"is 'X' and\", p2, \"is 'O'  (Randomly alloted)\" )   \n",
    "    \n",
    "\n",
    "    boardspaces = {'7': ' ' , '8': ' ' , '9': ' ' ,\n",
    "                   '4': ' ' , '5': ' ' , '6': ' ' ,                      #Board created using Dictionary\n",
    "                   '1': ' ' , '2': ' ' , '3': ' '  }\n",
    "            \n",
    "    def printBoard(board):\n",
    "        print(\"\\n\")\n",
    "        print(board['7'] + '|' + board['8'] + '|' + board['9'])\n",
    "        print('-+-+-')\n",
    "        print(board['4'] + '|' + board['5'] + '|' + board['6'])\n",
    "        print('-+-+-')\n",
    "        print(board['1'] + '|' + board['2'] + '|' + board['3'])\n",
    "    \n",
    "\n",
    "    turn = 'X'\n",
    "    chances = 0\n",
    "    while(True):    \n",
    "    \n",
    "                printBoard(boardspaces)\n",
    "            \n",
    "                if(turn == 'X'): p = p1\n",
    "                elif(turn == 'O'): p = p2\n",
    "            \n",
    "                print(\"\\n\")\n",
    "                print(\"It's\", p,\"'s turn. Your move?: \")\n",
    "\n",
    "                move = input(\"Move: \")        \n",
    "\n",
    "                if boardspaces[move] == ' ':\n",
    "                    boardspaces[move] = turn\n",
    "                    chances += 1\n",
    "                    \n",
    "                else:\n",
    "                    print(\"\\n\")\n",
    "                    print(\"That place is already filled! Choose another space.\")\n",
    "                    continue\n",
    "                \n",
    "                if boardspaces['7'] == boardspaces['8'] == boardspaces['9'] != ' ':\n",
    "                    printBoard(boardspaces)\n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break\n",
    "                elif boardspaces['4'] == boardspaces['5'] == boardspaces['6'] != ' ':\n",
    "                    printBoard(boardspaces)              \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break\n",
    "                elif boardspaces['1'] == boardspaces['2'] == boardspaces['3'] != ' ':\n",
    "                    printBoard(boardspaces)              \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break\n",
    "                elif boardspaces['1'] == boardspaces['4'] == boardspaces['7'] != ' ':\n",
    "                    printBoard(boardspaces)                \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break\n",
    "                elif boardspaces['2'] == boardspaces['5'] == boardspaces['8'] != ' ':\n",
    "                    printBoard(boardspaces)               \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break\n",
    "                elif boardspaces['3'] == boardspaces['6'] == boardspaces['9'] != ' ':\n",
    "                    printBoard(boardspaces)                \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break \n",
    "                elif boardspaces['7'] == boardspaces['5'] == boardspaces['3'] != ' ':\n",
    "                    printBoard(boardspaces)               \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break\n",
    "                elif boardspaces['1'] == boardspaces['5'] == boardspaces['9'] != ' ':\n",
    "                    printBoard(boardspaces)              \n",
    "                    print(\"\\n\")\n",
    "                    print(\" ****    And\",p,\"Wins the game!    ****\")                \n",
    "                    break    \n",
    "            \n",
    "                if turn =='X':\n",
    "                    turn = 'O'\n",
    "                                                                                #Change the turn\n",
    "                else:\n",
    "                    turn = 'X' \n",
    "                \n",
    "                if chances == 9:               \n",
    "                    print(\" ****    And it's a Tie!    ****\")\n",
    "                    break\n",
    "\n",
    "TicTacToe()\n",
    "\n",
    "print(\"\\n\")\n",
    "restart = input(\"Wanna play Again?(y/n): \")\n",
    "if restart == \"y\":\n",
    "    TicTacToe()\n",
    "else:\n",
    "    exit()\n",
    "\n",
    "    \n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
